# docker-compose.yml

version: "3"

services:
  portal-webapp:
    container_name: portal-webapp
    # The name of the image that will be created when building this container
    image: soren365/projectx-portal-webapp
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    # environment:
      # GRAPHQL_ENDPOINT: http://51.20.89.233:8280/query
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
